future: true
permalink: /:title/
url: http://hustcat.github.io
name: MinGO
author: mickey.shi
qq: 
email: mickey_shi@outllok.com
duoshuo: 
beian: 
cnzz: 
weibo: 
github: 
paginate: 20
highlighter: rouge
truncate: true
about: "MinGO"
