future: true
permalink: /:title/
url: https://shiminblog.github.io/
name: MinGO
author: mickey.shi
qq: 395128011
email: mickey_shi@outllok.com
fencoding: UTF-8
duoshuo: 
beian: 
cnzz: 
weibo: 
github: shiminblog/
paginate: 20
highlighter: rouge
truncate: true
about: "MinGO"
